#133842279 Accounts Tests Fixing
andela/healthchecks_asgards pull request #6
Opened 2016-11-28 11:03 UTC by andela-ian

#### What does this PR do?
It contains test fixes for the `accounts/tests`

#### Description of Task to be completed?
Have the following tests working
`hc/accounts/tests/test/test_check_token` 
`hc/accounts/tests/test/test_login`
`hc/accounts/tests/test/test_profile`
`hc/accounts/tests/test/test_switch_team`
`hc/accounts/tests/test/test_team_access_middleware`

#### How should this be manually tested?
After cloning the repo, cd into it and RUN `./manage.py test hc.accounts.tests`

#### What are the relevant pivotal tracker stories?
#133842279

2016-12-06 08:16 UTC, tonerdo requested changes
Hey guys, good job so far. Just a few changes and we should be good

2016-12-06 08:16 UTC, tsolarin commented on hc/accounts/tests/test_check_token.py
> +    unittest()
Why is this necessary?

2016-12-06 08:16 UTC, tsolarin commented on hc/accounts/tests/test_profile.py
> +        assert r.status_code == 200
Use `assert.Equals`

2016-12-06 08:41 UTC, andela-ian commented on hc/accounts/tests/test_profile.py
> +        assert r.status_code == 200
Noted

2016-12-07 08:35 UTC, tonerdo approved these changes

2016-12-07 08:35 UTC, merged